id: I318B33D3
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:11:45.730667
last_modified: 2023-02-08 15:11:45.730791
source_metadata:
  title: Maitreyavyākaraṇa
  language: zh
bases:
  5E0F:
    base_file: 5E0F.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
